# Generated by Django 5.2 on 2025-05-11 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_report_tour_booking_payment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
